apiVersion: apps/v1
kind: Deployment
metadata:
  name: fusion-manager
  labels:
    app.kubernetes.io/name: fusion-manager
    app.kubernetes.io/component: manager
    app.kubernetes.io/part-of: fusion
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fusion-manager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fusion-manager
        app.kubernetes.io/component: manager
        app.kubernetes.io/part-of: fusion
    spec:
      containers:
        - name: manager
          image: localhost/fusion:latest
          imagePullPolicy: Never
          command: ["./fusion"]
          args: ["manager", "-p", "5152", "--cert", "secrets/tls/tls.crt", "--key", "secrets/tls/tls.key"]
          ports:
            -  containerPort: 5152
          volumeMounts:
            - name: tls-secret
              mountPath: "/home/main/secrets/tls"
              readOnly: true
      volumes:
        - name: tls-secret
          secret:
            secretName: tls-secret
---
apiVersion: v1
kind: Service
metadata:
  name: fusion-manager-service
spec:
  selector:
    app.kubernetes.io/name: fusion-manager
  ports:
    - name: manager-grpc
      protocol: TCP
      port: 5152
      targetPort: 5152