FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y \
        curl \
        dnsutils \
        postgresql-client-14 \
    && \
    rm -rf /var/lib/apt/lists/*

RUN GO_MIGRATE_VERSION=4.15.2 && \
    curl -Lfso /tmp/migrate.tar.gz https://github.com/golang-migrate/migrate/releases/download/v${GO_MIGRATE_VERSION}/migrate.linux-amd64.tar.gz && \
    tar -xzf /tmp/migrate.tar.gz -C /bin && \
    chmod +x /bin/migrate && \
    rm /tmp/migrate.tar.gz

RUN DL_VERSION=0.2.2 && \
    curl -Lfso /tmp/dl.tar.gz https://github.com/gadget-inc/dateilager/releases/download/v${DL_VERSION}/dateilager-v${DL_VERSION}-linux-amd64.tar.gz && \
	tar -xzf /tmp/dl.tar.gz -C /bin && \
	mv bin/server bin/dateilager-server && \
	rm bin/client && \
	rm bin/webui && \
	rm /tmp/dl.tar.gz && \

    curl -Lfso /tmp/dl-migrations.tar.gz https://github.com/gadget-inc/dateilager/releases/download/v${DL_VERSION}/migrations.tar.gz && \
    mkdir -p /etc/dateilager && \
    tar -xzf /tmp/dl-migrations.tar.gz -C /etc/dateilager/ && \
    rm /tmp/dl-migrations.tar.gz

RUN useradd -ms /bin/bash main
USER main
WORKDIR /home/main

RUN mkdir -p secrets/tls
VOLUME secrets/tls

COPY bin/dateilager-server dateilager-server
COPY dateilager/entrypoint.sh entrypoint.sh
COPY development/paseto.pub secrets/paseto.pub

ENTRYPOINT ["./entrypoint.sh"]

CMD ["5051", "postgres://postgres@dl-postgres-service.fusion.svc.cluster.local", "dl"]